name: Auto Commit and Push

on:
  push:
    branches:
      - main  # Or your main branch name
    paths:
      - 'Procurement.xlsx'
      - 'risk.xlsx'
      - 'project_overview.xlsx'
      - 'solar_project_data.xlsx'

jobs:
  auto_commit_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Commit changes
        run: |
          git config user.name 'your_github_username'
          git config user.email 'your_github_email'
          git add Procurement.xlsx risk.xlsx project_overview.xlsx solar_project_data.xlsx
          git commit -m "Automatic update of Excel files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}